# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    tags: 'release/*'

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019]
    runs-on: ${{ matrix.os }}
    name: Build on ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    
    - name: Initialize environment
      shell: bash
      env:
        RUNNER_OS: ${{ runner.os }}
      run: |
        if [ $RUNNER_OS == 'Windows' ]; then
          echo ::set-env name=artifact-name::converter.exe
        else
          echo ::set-env name=artifact-name::converter
        fi
      
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create artifact
      run: pyinstaller --onefile converter.py
    
    - name: Update Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: ./dist/${{ env.artifact-name }}
        token: ${{ secrets.GITHUB_TOKEN }}
